1:HL["/_next/static/media/c9a5bc6a7c948fb0-s.p.woff2",{"as":"font","type":"font/woff2"}]
2:HL["/_next/static/css/98e4530578c425d7.css",{"as":"style"}]
0:["BTzIZmIeYXT3BlsSUt3SU",[[["",{"children":["swift",{"children":[["slug","Swift-%EC%98%88%EC%99%B8-%EC%B2%98%EB%A6%AC-%EA%B8%B0%EC%88%A0-%EB%B0%B0%EC%9A%B0%EA%B8%B0-try-catch-throws-%EC%82%AC%EC%9A%A9-%EB%B0%A9%EB%B2%95-a0412396","d"],{"children":["__PAGE__?{\"slug\":\"Swift-예외-처리-기술-배우기-try-catch-throws-사용-방법-a0412396\"}",{}]}]}]},"$undefined","$undefined",true],"$L3",[[["$","link","0",{"rel":"stylesheet","href":"/_next/static/css/98e4530578c425d7.css","precedence":"next"}]],"$L4"]]]]
5:I{"id":42879,"chunks":["185:static/chunks/app/layout-b198f10c98e34978.js"],"name":"GoogleAnalytics","async":false}
6:I{"id":47767,"chunks":["272:static/chunks/webpack-2f2428fbb7549638.js","971:static/chunks/fd9d1056-695585668d16e3fb.js","596:static/chunks/596-e6a99af3279f5db8.js"],"name":"default","async":false}
7:I{"id":57920,"chunks":["272:static/chunks/webpack-2f2428fbb7549638.js","971:static/chunks/fd9d1056-695585668d16e3fb.js","596:static/chunks/596-e6a99af3279f5db8.js"],"name":"default","async":false}
3:[null,["$","html",null,{"lang":"ko","children":[["$","$L5",null,{}],["$","body",null,{"className":"__className_aaf875","children":["$","$L6",null,{"parallelRouterKey":"children","segmentPath":["children"],"loading":"$undefined","loadingStyles":"$undefined","hasLoading":false,"error":"$undefined","errorStyles":"$undefined","template":["$","$L7",null,{}],"templateStyles":"$undefined","notFound":[["$","title",null,{"children":"404: This page could not be found."}],["$","div",null,{"style":{"fontFamily":"system-ui,\"Segoe UI\",Roboto,Helvetica,Arial,sans-serif,\"Apple Color Emoji\",\"Segoe UI Emoji\"","height":"100vh","textAlign":"center","display":"flex","flexDirection":"column","alignItems":"center","justifyContent":"center"},"children":["$","div",null,{"children":[["$","style",null,{"dangerouslySetInnerHTML":{"__html":"body{color:#000;background:#fff;margin:0}.next-error-h1{border-right:1px solid rgba(0,0,0,.3)}@media (prefers-color-scheme:dark){body{color:#fff;background:#000}.next-error-h1{border-right:1px solid rgba(255,255,255,.3)}}"}}],["$","h1",null,{"className":"next-error-h1","style":{"display":"inline-block","margin":"0 20px 0 0","padding":"0 23px 0 0","fontSize":24,"fontWeight":500,"verticalAlign":"top","lineHeight":"49px"},"children":"404"}],["$","div",null,{"style":{"display":"inline-block"},"children":["$","h2",null,{"style":{"fontSize":14,"fontWeight":400,"lineHeight":"49px","margin":0},"children":"This page could not be found."}]}]]}]}]],"notFoundStyles":[],"childProp":{"current":["$","$L6",null,{"parallelRouterKey":"children","segmentPath":["children","swift","children"],"loading":"$undefined","loadingStyles":"$undefined","hasLoading":false,"error":"$undefined","errorStyles":"$undefined","template":["$","$L7",null,{}],"templateStyles":"$undefined","notFound":"$undefined","notFoundStyles":"$undefined","childProp":{"current":["$","$L6",null,{"parallelRouterKey":"children","segmentPath":["children","swift","children",["slug","Swift-%EC%98%88%EC%99%B8-%EC%B2%98%EB%A6%AC-%EA%B8%B0%EC%88%A0-%EB%B0%B0%EC%9A%B0%EA%B8%B0-try-catch-throws-%EC%82%AC%EC%9A%A9-%EB%B0%A9%EB%B2%95-a0412396","d"],"children"],"loading":"$undefined","loadingStyles":"$undefined","hasLoading":false,"error":"$undefined","errorStyles":"$undefined","template":["$","$L7",null,{}],"templateStyles":"$undefined","notFound":"$undefined","notFoundStyles":"$undefined","childProp":{"current":["$L8","$L9",null],"segment":"__PAGE__?{\"slug\":\"Swift-예외-처리-기술-배우기-try-catch-throws-사용-방법-a0412396\"}"},"styles":[]}],"segment":["slug","Swift-%EC%98%88%EC%99%B8-%EC%B2%98%EB%A6%AC-%EA%B8%B0%EC%88%A0-%EB%B0%B0%EC%9A%B0%EA%B8%B0-try-catch-throws-%EC%82%AC%EC%9A%A9-%EB%B0%A9%EB%B2%95-a0412396","d"]},"styles":[]}],"segment":"swift"},"styles":[]}]}]]}],null]
4:[["$","meta","0",{"charSet":"utf-8"}],["$","title","1",{"children":"Swift 예외 처리 기술 배우기: try, catch, throws 사용 방법 | 마고자비 블로그"}],["$","meta","2",{"name":"description","content":"이 글에서는 Swift 프로그래밍 언어에서 예외 처리 기술인 `try`, `catch`, `throws`를 사용하는 방법에 대해 설명합니다. 예제 코드를 통해 이해를 돕고, 실제 프로젝트에서 어떻게 활용할 수 있는지 구체적으로 다룹니다."}],["$","meta","3",{"name":"keywords","content":"Swift,예외 처리,try-catch,throws"}],["$","meta","4",{"name":"viewport","content":"width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1, user-scalable=no"}],["$","link","5",{"rel":"canonical","href":"https://magomercy.com/swift/Swift-%EC%98%88%EC%99%B8-%EC%B2%98%EB%A6%AC-%EA%B8%B0%EC%88%A0-%EB%B0%B0%EC%9A%B0%EA%B8%B0-try-catch-throws-%EC%82%AC%EC%9A%A9-%EB%B0%A9%EB%B2%95-a0412396"}],["$","meta","6",{"name":"apple-mobile-web-app-capable","content":"yes"}],["$","meta","7",{"name":"apple-mobile-web-app-title","content":"Swift 예외 처리 기술 배우기: try, catch, throws 사용 방법 | 마고자비 블로그"}],["$","meta","8",{"name":"apple-mobile-web-app-status-bar-style","content":"default"}],["$","meta","9",{"property":"og:title","content":"Swift 예외 처리 기술 배우기: try, catch, throws 사용 방법 | 마고자비 블로그"}],["$","meta","10",{"property":"og:description","content":"이 글에서는 Swift 프로그래밍 언어에서 예외 처리 기술인 `try`, `catch`, `throws`를 사용하는 방법에 대해 설명합니다. 예제 코드를 통해 이해를 돕고, 실제 프로젝트에서 어떻게 활용할 수 있는지 구체적으로 다룹니다."}],["$","meta","11",{"property":"og:url","content":"https://magomercy.com/swift/Swift-%EC%98%88%EC%99%B8-%EC%B2%98%EB%A6%AC-%EA%B8%B0%EC%88%A0-%EB%B0%B0%EC%9A%B0%EA%B8%B0-try-catch-throws-%EC%82%AC%EC%9A%A9-%EB%B0%A9%EB%B2%95-a0412396"}],["$","meta","12",{"property":"og:site_name","content":"마고자비 블로그 | 마구잡이로 하고 싶은 것을 합니다."}],["$","meta","13",{"property":"og:locale","content":"kr"}],["$","meta","14",{"property":"og:image","content":"https://magomercy.com/images/swiftBanner4.jpg"}],["$","meta","15",{"property":"og:type","content":"website"}],["$","meta","16",{"name":"twitter:card","content":"summary"}],["$","meta","17",{"name":"twitter:creator","content":"마고자비 블로그"}],["$","meta","18",{"name":"twitter:title","content":"Swift 예외 처리 기술 배우기: try, catch, throws 사용 방법 | 마고자비 블로그"}],["$","meta","19",{"name":"twitter:description","content":"이 글에서는 Swift 프로그래밍 언어에서 예외 처리 기술인 `try`, `catch`, `throws`를 사용하는 방법에 대해 설명합니다. 예제 코드를 통해 이해를 돕고, 실제 프로젝트에서 어떻게 활용할 수 있는지 구체적으로 다룹니다."}],["$","meta","20",{"name":"twitter:image","content":"https://magomercy.com/images/swiftBanner4.jpg"}],["$","link","21",{"rel":"icon","href":"https://magomercy.com/favicon32.png"}],["$","link","22",{"rel":"apple-touch-icon","href":"https://magomercy.com/favicon32.png"}],["$","meta","23",{"name":"next-size-adjust"}]]
a:I{"id":22873,"chunks":["986:static/chunks/986-5f83c849e7b0dffa.js","754:static/chunks/754-8b5d90286cb88ad9.js","543:static/chunks/543-fe4d83430fed7822.js","288:static/chunks/app/swift/[slug]/page-4841b882b9c15aba.js"],"name":"","async":false}
b:I{"id":84423,"chunks":["986:static/chunks/986-5f83c849e7b0dffa.js","754:static/chunks/754-8b5d90286cb88ad9.js","543:static/chunks/543-fe4d83430fed7822.js","288:static/chunks/app/swift/[slug]/page-4841b882b9c15aba.js"],"name":"","async":false}
c:I{"id":2346,"chunks":["986:static/chunks/986-5f83c849e7b0dffa.js","754:static/chunks/754-8b5d90286cb88ad9.js","543:static/chunks/543-fe4d83430fed7822.js","288:static/chunks/app/swift/[slug]/page-4841b882b9c15aba.js"],"name":"","async":false}
d:I{"id":67490,"chunks":["986:static/chunks/986-5f83c849e7b0dffa.js","754:static/chunks/754-8b5d90286cb88ad9.js","543:static/chunks/543-fe4d83430fed7822.js","288:static/chunks/app/swift/[slug]/page-4841b882b9c15aba.js"],"name":"MarkDownCode","async":false}
e:I{"id":87272,"chunks":["986:static/chunks/986-5f83c849e7b0dffa.js","754:static/chunks/754-8b5d90286cb88ad9.js","543:static/chunks/543-fe4d83430fed7822.js","288:static/chunks/app/swift/[slug]/page-4841b882b9c15aba.js"],"name":"","async":false}
f:I{"id":55026,"chunks":["986:static/chunks/986-5f83c849e7b0dffa.js","754:static/chunks/754-8b5d90286cb88ad9.js","543:static/chunks/543-fe4d83430fed7822.js","288:static/chunks/app/swift/[slug]/page-4841b882b9c15aba.js"],"name":"","async":false}
9:[["$","$La",null,{"language":"kr","screenType":"ARTICLE_DETAIL"}],["$","section",null,{"className":"flex fixed top-0 left-0 w-full  md:h-[600px] h-[300px] justify-center","style":{"backgroundImage":"url(/images/swiftBanner4.jpg)","backgroundPosition":"center","backgroundSize":"contain","backgroundRepeat":"no-repeat"},"children":[["$","div",null,{"className":"w-full md:h-[600px] h-[300px]  bg-[#171E24] bg-opacity-[0.35] absolute top-0 left-0"}],["$","div",null,{"className":"hidden md:flex flex-col justify-end w-[100%] md:w-[700px] px-[20px] pb-[100px]","children":["$","h1",null,{"className":"font-semibold text-[40px] text-gray-100 text-shadow-default z-40","children":"Swift 예외 처리 기술 배우기: try, catch, throws 사용 방법"}]}]]}],["$","main",null,{"className":"flex flex-row justify-center md:py-[120px] py-[60px] bg-white md:mt-[600px] mt-[300px] relative z-30 ","children":[["$","div",null,{"className":"xl:flex hidden w-[300px]","children":["$","div",null,{"className":"toc sticky top-[90px] flex flex-col","children":["$","$Lb",null,{}]}]}],["$","article",null,{"className":"flex flex-col w-full md:w-[600px] px-[20px] md:px-[0px] gap-[40px]","children":[["$","div",null,{"className":"md:hidden border-b-[0.6px] pb-[40px] border-gray-200","children":["$","h1",null,{"className":"text-[28px] font-bold leading-[150%]","children":"Swift 예외 처리 기술 배우기: try, catch, throws 사용 방법"}]}],["$","div",null,{"className":"flex flex-col","children":[["$","$Lc",null,{}],["$","div",null,{"children":["작성일 : ",["$","time",null,{"children":"2024-07-07"}]]}]]}],["$","div",null,{"children":["$","div",null,{"className":"md-to-html","children":[["$","h1",null,{"id":"6bdb6dee","className":"md:text-[42px] text-[26px] font-bold leading-[150%] md:py-[50px] py-[30px] text-gray-900","children":"Swift 예외 처리 기술 배우기: try, catch, throws 사용 방법"}],"\n",["$","p",null,{"className":"md:text-[16px] text-[15px] leading-[180%] text-gray-800 md:py-[20px] py-[20px]","children":["Swift는 안전하고 간결한 예외 처리를 위해 ",["$","$Ld",null,{"props":{"node":{"type":"element","tagName":"code","properties":{},"children":[{"type":"text","value":"try","position":{"start":{"line":4,"column":27,"offset":75},"end":{"line":4,"column":32,"offset":80}}}],"position":{"start":{"line":4,"column":27,"offset":75},"end":{"line":4,"column":32,"offset":80}}},"children":"try"}}],", ",["$","$Ld",null,{"props":{"node":{"type":"element","tagName":"code","properties":{},"children":[{"type":"text","value":"catch","position":{"start":{"line":4,"column":34,"offset":82},"end":{"line":4,"column":41,"offset":89}}}],"position":{"start":{"line":4,"column":34,"offset":82},"end":{"line":4,"column":41,"offset":89}}},"children":"catch"}}],", ",["$","$Ld",null,{"props":{"node":{"type":"element","tagName":"code","properties":{},"children":[{"type":"text","value":"throws","position":{"start":{"line":4,"column":43,"offset":91},"end":{"line":4,"column":51,"offset":99}}}],"position":{"start":{"line":4,"column":43,"offset":91},"end":{"line":4,"column":51,"offset":99}}},"children":"throws"}}]," 키워드를 제공합니다. 이 글에서는 이 키워드들이 어떤 역할을 하고, 어떻게 활용할 수 있는지에 대해 살펴보겠습니다. 먼저 예외 처리의 기본 개념을 살펴보고, 다양한 사용 사례를 통해 이해를 깊이도록 하겠습니다."]}],"\n",["$","h2",null,{"id":"2c12d68e","className":"md:text-[32px] text-[22px] font-semibold leading-[145%] md:py-[30px] py-[20px] text-gray-800","children":"예외 처리 기본 개념"}],"\n",["$","p",null,{"className":"md:text-[16px] text-[15px] leading-[180%] text-gray-800 md:py-[20px] py-[20px]","children":"Swift에서는 함수나 메서드가 오류를 발생시킬 수 있는 경우 이를 명시적으로 선언하고 처리할 수 있습니다. 예외 처리는 주로 함수의 정상적인 흐름을 방해할 수 있는 예외 상황을 처리하는데 사용됩니다. 이를 통해 예기치 못한 오류로 인해 프로그램이 중단되는 것을 방지할 수 있습니다."}],"\n",["$","p",null,{"className":"md:text-[16px] text-[15px] leading-[180%] text-gray-800 md:py-[20px] py-[20px]","children":"Swift에서 예외 처리를 하기 위해서는 세 가지 주요 키워드를 사용합니다:"}],"\n",["$","ol","ol-0",{"children":["\n",["$","li","li-0",{"children":[["$","$Ld",null,{"props":{"node":{"type":"element","tagName":"code","properties":{},"children":[{"type":"text","value":"throws","position":{"start":{"line":12,"column":4,"offset":442},"end":{"line":12,"column":12,"offset":450}}}],"position":{"start":{"line":12,"column":4,"offset":442},"end":{"line":12,"column":12,"offset":450}}},"children":"throws"}}],": 함수가 오류를 던질 수 있음을 표시합니다."]}],"\n",["$","li","li-1",{"children":[["$","$Ld",null,{"props":{"node":{"type":"element","tagName":"code","properties":{},"children":[{"type":"text","value":"try","position":{"start":{"line":13,"column":4,"offset":479},"end":{"line":13,"column":9,"offset":484}}}],"position":{"start":{"line":13,"column":4,"offset":479},"end":{"line":13,"column":9,"offset":484}}},"children":"try"}}],": 오류가 발생할 수 있는 코드 앞에 사용합니다."]}],"\n",["$","li","li-2",{"children":[["$","$Ld",null,{"props":{"node":{"type":"element","tagName":"code","properties":{},"children":[{"type":"text","value":"catch","position":{"start":{"line":14,"column":4,"offset":515},"end":{"line":14,"column":11,"offset":522}}}],"position":{"start":{"line":14,"column":4,"offset":515},"end":{"line":14,"column":11,"offset":522}}},"children":"catch"}}],": 던져진 오류를 처리합니다."]}],"\n"]}],"\n",["$","h3",null,{"id":"da39a3ee","className":"md:text-[24px] text-[20px] font-medium leading-[140%] md:py-[30px] py-[18px] text-gray-800","children":[["$","$Ld",null,{"props":{"node":{"type":"element","tagName":"code","properties":{},"children":[{"type":"text","value":"throws","position":{"start":{"line":16,"column":5,"offset":544},"end":{"line":16,"column":13,"offset":552}}}],"position":{"start":{"line":16,"column":5,"offset":544},"end":{"line":16,"column":13,"offset":552}}},"children":"throws"}}]," 키워드"]}],"\n",["$","p",null,{"className":"md:text-[16px] text-[15px] leading-[180%] text-gray-800 md:py-[20px] py-[20px]","children":[["$","$Ld",null,{"props":{"node":{"type":"element","tagName":"code","properties":{},"children":[{"type":"text","value":"throws","position":{"start":{"line":18,"column":1,"offset":558},"end":{"line":18,"column":9,"offset":566}}}],"position":{"start":{"line":18,"column":1,"offset":558},"end":{"line":18,"column":9,"offset":566}}},"children":"throws"}}]," 키워드는 함수나 메서드가 오류를 던질 수 있음을 나타냅니다. 이는 함수 선언부에서 사용하는데, 함수의 반환 타입 뒤에 ",["$","$Ld",null,{"props":{"node":{"type":"element","tagName":"code","properties":{},"children":[{"type":"text","value":"throws","position":{"start":{"line":18,"column":76,"offset":633},"end":{"line":18,"column":84,"offset":641}}}],"position":{"start":{"line":18,"column":76,"offset":633},"end":{"line":18,"column":84,"offset":641}}},"children":"throws"}}]," 키워드를 추가합니다. 예를 들어, 다음은 파일을 읽는 과정에서 오류가 발생할 수 있는 함수를 정의한 것입니다:"]}],"\n",["$","pre","pre-0",{"children":["$","$Ld",null,{"props":{"className":"language-swift","node":{"type":"element","tagName":"code","properties":{"className":["language-swift"]},"children":[{"type":"text","value":"func readFile(at path: String) throws -> String {\n    // 파일을 읽는 코드\n}\n"}],"position":{"start":{"line":20,"column":1,"offset":705},"end":{"line":24,"column":4,"offset":786}}},"children":"func readFile(at path: String) throws -> String {\n    // 파일을 읽는 코드\n}\n"}}]}],"\n",["$","p",null,{"className":"md:text-[16px] text-[15px] leading-[180%] text-gray-800 md:py-[20px] py-[20px]","children":"이 함수는 파일 경로를 입력으로 받아 파일 내용을 문자열로 반환하려고 하지만, 파일이 존재하지 않거나 읽기 권한이 없는 등의 상황에서 오류를 던질 수 있습니다."}],"\n",["$","h3",null,{"id":"da39a3ee","className":"md:text-[24px] text-[20px] font-medium leading-[140%] md:py-[30px] py-[18px] text-gray-800","children":[["$","$Ld",null,{"props":{"node":{"type":"element","tagName":"code","properties":{},"children":[{"type":"text","value":"try","position":{"start":{"line":28,"column":5,"offset":883},"end":{"line":28,"column":10,"offset":888}}}],"position":{"start":{"line":28,"column":5,"offset":883},"end":{"line":28,"column":10,"offset":888}}},"children":"try"}}]," 키워드"]}],"\n",["$","p",null,{"className":"md:text-[16px] text-[15px] leading-[180%] text-gray-800 md:py-[20px] py-[20px]","children":[["$","$Ld",null,{"props":{"node":{"type":"element","tagName":"code","properties":{},"children":[{"type":"text","value":"try","position":{"start":{"line":30,"column":1,"offset":894},"end":{"line":30,"column":6,"offset":899}}}],"position":{"start":{"line":30,"column":1,"offset":894},"end":{"line":30,"column":6,"offset":899}}},"children":"try"}}]," 키워드는 오류를 던질 수 있는 함수를 호출할 때 사용됩니다. ",["$","$Ld",null,{"props":{"node":{"type":"element","tagName":"code","properties":{},"children":[{"type":"text","value":"try","position":{"start":{"line":30,"column":41,"offset":934},"end":{"line":30,"column":46,"offset":939}}}],"position":{"start":{"line":30,"column":41,"offset":934},"end":{"line":30,"column":46,"offset":939}}},"children":"try"}}]," 키워드는 오류가 발생할 수 있는 코드 블록 앞에 위치하여 예외 처리를 위한 준비가 되었음을 나타냅니다. 예를 들어, ",["$","$Ld",null,{"props":{"node":{"type":"element","tagName":"code","properties":{},"children":[{"type":"text","value":"readFile","position":{"start":{"line":30,"column":112,"offset":1005},"end":{"line":30,"column":122,"offset":1015}}}],"position":{"start":{"line":30,"column":112,"offset":1005},"end":{"line":30,"column":122,"offset":1015}}},"children":"readFile"}}]," 함수를 사용하는 코드에서 다음과 같이 사용할 수 있습니다:"]}],"\n",["$","pre","pre-1",{"children":["$","$Ld",null,{"props":{"className":"language-swift","node":{"type":"element","tagName":"code","properties":{"className":["language-swift"]},"children":[{"type":"text","value":"let filePath = \"path/to/file.txt\"\nlet fileContent: String\n\n do {\n    fileContent = try readFile(at: filePath)\n} catch {\n    print(\"파일을 읽는 도중 오류 발생: \\(error)\")\n}\n"}],"position":{"start":{"line":32,"column":1,"offset":1050},"end":{"line":41,"column":4,"offset":1223}}},"children":"let filePath = \"path/to/file.txt\"\nlet fileContent: String\n\n do {\n    fileContent = try readFile(at: filePath)\n} catch {\n    print(\"파일을 읽는 도중 오류 발생: \\(error)\")\n}\n"}}]}],"\n",["$","p",null,{"className":"md:text-[16px] text-[15px] leading-[180%] text-gray-800 md:py-[20px] py-[20px]","children":["여기서 ",["$","$Ld",null,{"props":{"node":{"type":"element","tagName":"code","properties":{},"children":[{"type":"text","value":"try","position":{"start":{"line":43,"column":5,"offset":1229},"end":{"line":43,"column":10,"offset":1234}}}],"position":{"start":{"line":43,"column":5,"offset":1229},"end":{"line":43,"column":10,"offset":1234}}},"children":"try"}}]," 키워드는 ",["$","$Ld",null,{"props":{"node":{"type":"element","tagName":"code","properties":{},"children":[{"type":"text","value":"readFile","position":{"start":{"line":43,"column":16,"offset":1240},"end":{"line":43,"column":26,"offset":1250}}}],"position":{"start":{"line":43,"column":16,"offset":1240},"end":{"line":43,"column":26,"offset":1250}}},"children":"readFile"}}]," 함수가 오류를 던질 수 있다는 것을 명시합니다. 실제로 오류가 발생하면 ",["$","$Ld",null,{"props":{"node":{"type":"element","tagName":"code","properties":{},"children":[{"type":"text","value":"catch","position":{"start":{"line":43,"column":67,"offset":1291},"end":{"line":43,"column":74,"offset":1298}}}],"position":{"start":{"line":43,"column":67,"offset":1291},"end":{"line":43,"column":74,"offset":1298}}},"children":"catch"}}]," 블록으로 제어가 이동합니다."]}],"\n",["$","h2",null,{"id":"da39a3ee","className":"md:text-[32px] text-[22px] font-semibold leading-[145%] md:py-[30px] py-[20px] text-gray-800","children":[["$","$Ld",null,{"props":{"node":{"type":"element","tagName":"code","properties":{},"children":[{"type":"text","value":"do-catch","position":{"start":{"line":45,"column":4,"offset":1319},"end":{"line":45,"column":14,"offset":1329}}}],"position":{"start":{"line":45,"column":4,"offset":1319},"end":{"line":45,"column":14,"offset":1329}}},"children":"do-catch"}}]," 구문"]}],"\n",["$","p",null,{"className":"md:text-[16px] text-[15px] leading-[180%] text-gray-800 md:py-[20px] py-[20px]","children":[["$","$Ld",null,{"props":{"node":{"type":"element","tagName":"code","properties":{},"children":[{"type":"text","value":"do-catch","position":{"start":{"line":47,"column":1,"offset":1334},"end":{"line":47,"column":11,"offset":1344}}}],"position":{"start":{"line":47,"column":1,"offset":1334},"end":{"line":47,"column":11,"offset":1344}}},"children":"do-catch"}}]," 구문은 오류 처리의 핵심 구성 요소입니다. ",["$","$Ld",null,{"props":{"node":{"type":"element","tagName":"code","properties":{},"children":[{"type":"text","value":"do","position":{"start":{"line":47,"column":36,"offset":1369},"end":{"line":47,"column":40,"offset":1373}}}],"position":{"start":{"line":47,"column":36,"offset":1369},"end":{"line":47,"column":40,"offset":1373}}},"children":"do"}}]," 블록 내에서 오류가 발생할 수 있는 코드를 실행하고, ",["$","$Ld",null,{"props":{"node":{"type":"element","tagName":"code","properties":{},"children":[{"type":"text","value":"catch","position":{"start":{"line":47,"column":71,"offset":1404},"end":{"line":47,"column":78,"offset":1411}}}],"position":{"start":{"line":47,"column":71,"offset":1404},"end":{"line":47,"column":78,"offset":1411}}},"children":"catch"}}]," 블록 내에서 발생한 오류를 처리합니다. 예를 들어, 다음은 파일을 읽는 예제입니다:"]}],"\n",["$","pre","pre-2",{"children":["$","$Ld",null,{"props":{"className":"language-swift","node":{"type":"element","tagName":"code","properties":{"className":["language-swift"]},"children":[{"type":"text","value":"func readFileContents() {\n    let filePath = \"path/to/file.txt\"\n    do {\n        let content = try readFile(at: filePath)\n        print(content)\n    } catch let error as FileError {\n        switch error {\n        case .notFound:\n            print(\"파일을 찾을 수 없습니다.\")\n        case .noPermission:\n            print(\"파일을 읽을 권한이 없습니다.\")\n        default:\n            print(\"알 수 없는 오류가 발생했습니다: \\(error)\")\n        }\n    } catch {\n        print(\"기타 오류 발생: \\(error)\")\n    }\n}\n"}],"position":{"start":{"line":49,"column":1,"offset":1460},"end":{"line":68,"column":4,"offset":1937}}},"children":"func readFileContents() {\n    let filePath = \"path/to/file.txt\"\n    do {\n        let content = try readFile(at: filePath)\n        print(content)\n    } catch let error as FileError {\n        switch error {\n        case .notFound:\n            print(\"파일을 찾을 수 없습니다.\")\n        case .noPermission:\n            print(\"파일을 읽을 권한이 없습니다.\")\n        default:\n            print(\"알 수 없는 오류가 발생했습니다: \\(error)\")\n        }\n    } catch {\n        print(\"기타 오류 발생: \\(error)\")\n    }\n}\n"}}]}],"\n",["$","p",null,{"className":"md:text-[16px] text-[15px] leading-[180%] text-gray-800 md:py-[20px] py-[20px]","children":["여기서는 여러 종류의 오류를 처리하기 위해 ",["$","$Ld",null,{"props":{"node":{"type":"element","tagName":"code","properties":{},"children":[{"type":"text","value":"catch","position":{"start":{"line":70,"column":25,"offset":1963},"end":{"line":70,"column":32,"offset":1970}}}],"position":{"start":{"line":70,"column":25,"offset":1963},"end":{"line":70,"column":32,"offset":1970}}},"children":"catch"}}]," 블록 안에 오류 타입을 명시적으로 구분하여 처리하고 있습니다. 이는 오류의 종류에 따라 적절한 대응을 할 수 있도록 도와줍니다."]}],"\n",["$","h2",null,{"id":"da39a3ee","className":"md:text-[32px] text-[22px] font-semibold leading-[145%] md:py-[30px] py-[20px] text-gray-800","children":[["$","$Ld",null,{"props":{"node":{"type":"element","tagName":"code","properties":{},"children":[{"type":"text","value":"rethrows","position":{"start":{"line":72,"column":4,"offset":2047},"end":{"line":72,"column":14,"offset":2057}}}],"position":{"start":{"line":72,"column":4,"offset":2047},"end":{"line":72,"column":14,"offset":2057}}},"children":"rethrows"}}]," 키워드"]}],"\n",["$","p",null,{"className":"md:text-[16px] text-[15px] leading-[180%] text-gray-800 md:py-[20px] py-[20px]","children":[["$","$Ld",null,{"props":{"node":{"type":"element","tagName":"code","properties":{},"children":[{"type":"text","value":"rethrows","position":{"start":{"line":74,"column":1,"offset":2063},"end":{"line":74,"column":11,"offset":2073}}}],"position":{"start":{"line":74,"column":1,"offset":2063},"end":{"line":74,"column":11,"offset":2073}}},"children":"rethrows"}}]," 키워드는 함수가 인자로 받은 클로저가 오류를 던질 경우, 해당 오류를 다시 던질 수 있음을 나타냅니다. ",["$","$Ld",null,{"props":{"node":{"type":"element","tagName":"code","properties":{},"children":[{"type":"text","value":"rethrows","position":{"start":{"line":74,"column":70,"offset":2132},"end":{"line":74,"column":80,"offset":2142}}}],"position":{"start":{"line":74,"column":70,"offset":2132},"end":{"line":74,"column":80,"offset":2142}}},"children":"rethrows"}}]," 키워드는 주로 고차 함수(high-order function)에서 사용됩니다. 예를 들어, 다음은 오류를 던질 수 있는 클로저를 인자로 받는 함수입니다:"]}],"\n",["$","pre","pre-3",{"children":["$","$Ld",null,{"props":{"className":"language-swift","node":{"type":"element","tagName":"code","properties":{"className":["language-swift"]},"children":[{"type":"text","value":"func performOperation(with closure: () throws -> Void) rethrows {\n    try closure()\n}\n"}],"position":{"start":{"line":76,"column":1,"offset":2230},"end":{"line":80,"column":4,"offset":2328}}},"children":"func performOperation(with closure: () throws -> Void) rethrows {\n    try closure()\n}\n"}}]}],"\n",["$","p",null,{"className":"md:text-[16px] text-[15px] leading-[180%] text-gray-800 md:py-[20px] py-[20px]","children":["이 함수는 ",["$","$Ld",null,{"props":{"node":{"type":"element","tagName":"code","properties":{},"children":[{"type":"text","value":"closure","position":{"start":{"line":82,"column":7,"offset":2336},"end":{"line":82,"column":16,"offset":2345}}}],"position":{"start":{"line":82,"column":7,"offset":2336},"end":{"line":82,"column":16,"offset":2345}}},"children":"closure"}}],"가 오류를 던질 경우, 이를 다시 호출자에게 던질 수 있습니다. 이렇게 하면 오류 처리 로직을 재사용 가능하게 작성할 수 있습니다."]}],"\n",["$","h2",null,{"id":"9bd0316e","className":"md:text-[32px] text-[22px] font-semibold leading-[145%] md:py-[30px] py-[20px] text-gray-800","children":"실제 사용 사례"}],"\n",["$","h3",null,{"id":"086258f5","className":"md:text-[24px] text-[20px] font-medium leading-[140%] md:py-[30px] py-[18px] text-gray-800","children":"파일 처리"}],"\n",["$","p",null,{"className":"md:text-[16px] text-[15px] leading-[180%] text-gray-800 md:py-[20px] py-[20px]","children":"파일 시스템과 상호작용할 때는 다양한 예외 상황이 발생할 수 있습니다. 파일이 존재하지 않거나, 파일을 읽을 권한이 없거나, 파일 읽기/쓰기 중 오류가 발생할 수 있습니다. 아래는 파일을 읽는 예제입니다:"}],"\n",["$","pre","pre-4",{"children":["$","$Ld",null,{"props":{"className":"language-swift","node":{"type":"element","tagName":"code","properties":{"className":["language-swift"]},"children":[{"type":"text","value":"enum FileError: Error {\n    case notFound\n    case noPermission\n}\n\nfunc readFile(at path: String) throws -> String {\n    // 실제 파일 읽기 코드 (예외 처리를 위해 단순화됨)\n    guard path == \"valid/path\" else {\n        throw FileError.notFound\n    }\n    return \"파일 내용\"\n}\n\nlet filePath = \"valid/path\"\ndo {\n    let content = try readFile(at: filePath)\n    print(content)\n} catch FileError.notFound {\n    print(\"파일을 찾을 수 없습니다.\")\n} catch FileError.noPermission {\n    print(\"파일을 읽을 권한이 없습니다.\")\n} catch {\n    print(\"알 수 없는 오류가 발생했습니다: \\(error)\")\n}\n"}],"position":{"start":{"line":90,"column":1,"offset":2560},"end":{"line":115,"column":4,"offset":3094}}},"children":"enum FileError: Error {\n    case notFound\n    case noPermission\n}\n\nfunc readFile(at path: String) throws -> String {\n    // 실제 파일 읽기 코드 (예외 처리를 위해 단순화됨)\n    guard path == \"valid/path\" else {\n        throw FileError.notFound\n    }\n    return \"파일 내용\"\n}\n\nlet filePath = \"valid/path\"\ndo {\n    let content = try readFile(at: filePath)\n    print(content)\n} catch FileError.notFound {\n    print(\"파일을 찾을 수 없습니다.\")\n} catch FileError.noPermission {\n    print(\"파일을 읽을 권한이 없습니다.\")\n} catch {\n    print(\"알 수 없는 오류가 발생했습니다: \\(error)\")\n}\n"}}]}],"\n",["$","h3",null,{"id":"3a7ae8a6","className":"md:text-[24px] text-[20px] font-medium leading-[140%] md:py-[30px] py-[18px] text-gray-800","children":"네트워크 요청"}],"\n",["$","p",null,{"className":"md:text-[16px] text-[15px] leading-[180%] text-gray-800 md:py-[20px] py-[20px]","children":"네트워크 작업도 많은 예외 상황을 포함합니다. 예를 들어, 서버가 응답하지 않거나, 네트워크 연결이 끊기거나, 데이터가 사용할 수 없는 형식일 수 있습니다. 다음은 네트워크 요청의 예제입니다:"}],"\n",["$","pre","pre-5",{"children":["$","$Ld",null,{"props":{"className":"language-swift","node":{"type":"element","tagName":"code","properties":{"className":["language-swift"]},"children":[{"type":"text","value":"enum NetworkError: Error {\n    case badURL\n    case requestFailed\n    case unknown\n}\n\nfunc fetchData(from urlString: String) throws -> Data {\n    guard let url = URL(string: urlString) else {\n        throw NetworkError.badURL\n    }\n\n    // 실제 네트워크 요청 코드 단순화됨\n    guard let data = Data(base64Encoded: \"response data\") else {\n        throw NetworkError.requestFailed\n    }\n    return data\n}\n\nlet urlString = \"http://valid.url\"\ndo {\n    let data = try fetchData(from: urlString)\n    print(\"데이터 받음: \\(data)\")\n} catch NetworkError.badURL {\n    print(\"잘못된 URL입니다.\")\n} catch NetworkError.requestFailed {\n    print(\"네트워크 요청에 실패했습니다.\")\n} catch {\n    print(\"알 수 없는 오류가 발생했습니다: \\(error)\")\n}\n"}],"position":{"start":{"line":121,"column":1,"offset":3218},"end":{"line":151,"column":4,"offset":3910}}},"children":"enum NetworkError: Error {\n    case badURL\n    case requestFailed\n    case unknown\n}\n\nfunc fetchData(from urlString: String) throws -> Data {\n    guard let url = URL(string: urlString) else {\n        throw NetworkError.badURL\n    }\n\n    // 실제 네트워크 요청 코드 단순화됨\n    guard let data = Data(base64Encoded: \"response data\") else {\n        throw NetworkError.requestFailed\n    }\n    return data\n}\n\nlet urlString = \"http://valid.url\"\ndo {\n    let data = try fetchData(from: urlString)\n    print(\"데이터 받음: \\(data)\")\n} catch NetworkError.badURL {\n    print(\"잘못된 URL입니다.\")\n} catch NetworkError.requestFailed {\n    print(\"네트워크 요청에 실패했습니다.\")\n} catch {\n    print(\"알 수 없는 오류가 발생했습니다: \\(error)\")\n}\n"}}]}],"\n",["$","h2",null,{"id":"5b12bcf2","className":"md:text-[32px] text-[22px] font-semibold leading-[145%] md:py-[30px] py-[20px] text-gray-800","children":"결론"}],"\n",["$","p",null,{"className":"md:text-[16px] text-[15px] leading-[180%] text-gray-800 md:py-[20px] py-[20px]","children":["Swift의 예외 처리 시스템은 매우 강력하면서도 간결하게 사용할 수 있습니다. ",["$","$Ld",null,{"props":{"node":{"type":"element","tagName":"code","properties":{},"children":[{"type":"text","value":"try","position":{"start":{"line":155,"column":46,"offset":3964},"end":{"line":155,"column":51,"offset":3969}}}],"position":{"start":{"line":155,"column":46,"offset":3964},"end":{"line":155,"column":51,"offset":3969}}},"children":"try"}}],", ",["$","$Ld",null,{"props":{"node":{"type":"element","tagName":"code","properties":{},"children":[{"type":"text","value":"catch","position":{"start":{"line":155,"column":53,"offset":3971},"end":{"line":155,"column":60,"offset":3978}}}],"position":{"start":{"line":155,"column":53,"offset":3971},"end":{"line":155,"column":60,"offset":3978}}},"children":"catch"}}],", ",["$","$Ld",null,{"props":{"node":{"type":"element","tagName":"code","properties":{},"children":[{"type":"text","value":"throws","position":{"start":{"line":155,"column":62,"offset":3980},"end":{"line":155,"column":70,"offset":3988}}}],"position":{"start":{"line":155,"column":62,"offset":3980},"end":{"line":155,"column":70,"offset":3988}}},"children":"throws"}}],", ",["$","$Ld",null,{"props":{"node":{"type":"element","tagName":"code","properties":{},"children":[{"type":"text","value":"rethrows","position":{"start":{"line":155,"column":72,"offset":3990},"end":{"line":155,"column":82,"offset":4000}}}],"position":{"start":{"line":155,"column":72,"offset":3990},"end":{"line":155,"column":82,"offset":4000}}},"children":"rethrows"}}]," 키워드를 이용하여 오류를 명확하게 처리할 수 있습니다. 이를 통해 코드의 신뢰성을 높이고, 예외 상황에서도 안정적으로 동작하는 애플리케이션을 만들 수 있습니다. 이러한 예외 처리 기술을 제대로 이해하고 활용하면, 더욱 견고한 Swift 애플리케이션을 개발할 수 있을 것입니다."]}]]}]}],["$","$Le",null,{}]]}],["$","div",null,{"className":"xl:flex hidden w-[300px]","children":["$","$Lf",null,{"articleTitle":"Swift 예외 처리 기술 배우기: try, catch, throws 사용 방법","toc":[{"tagName":"h1","title":"Swift 예외 처리 기술 배우기: try, catch, throws 사용 방법","id":"6bdb6dee"},{"tagName":"h2","title":"예외 처리 기본 개념","id":"2c12d68e"},{"tagName":"h3","title":"$undefined","id":""},{"tagName":"h3","title":"$undefined","id":""},{"tagName":"h2","title":"$undefined","id":""},{"tagName":"h2","title":"$undefined","id":""},{"tagName":"h2","title":"실제 사용 사례","id":"9bd0316e"},{"tagName":"h3","title":"파일 처리","id":"086258f5"},{"tagName":"h3","title":"네트워크 요청","id":"3a7ae8a6"},{"tagName":"h2","title":"결론","id":"5b12bcf2"}],"language":"kr"}]}]]}]]
8:null
